name: Release
on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go: ['1.19', '1.20', '1.21']
    name: Go ${{ matrix.go }} test
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}
      - run: go test -race -v -coverprofile=profile.cov ./pkg/...
      - uses: codecov/codecov-action@v4.1.1
        with:
          file: ./profile.cov
          name: codecov-go
  release:
    runs-on: ubuntu-22.04
    needs: [test]
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Source checkout
      uses: actions/checkout@v4
    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      with:
        dry_run: false
        semantic_version: 18.0.1
        extra_plugins: |
          @semantic-release/exec@6.0.3
