// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/zitadel/saml/pkg/provider (interfaces: Storage)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	key "github.com/zitadel/saml/pkg/provider/key"
	models "github.com/zitadel/saml/pkg/provider/models"
	serviceprovider "github.com/zitadel/saml/pkg/provider/serviceprovider"
	samlp "github.com/zitadel/saml/pkg/provider/xml/samlp"
	reflect "reflect"
)

// MockStorage is a mock of Storage interface
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AuthRequestByID mocks base method
func (m *MockStorage) AuthRequestByID(arg0 context.Context, arg1 string) (models.AuthRequestInt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthRequestByID", arg0, arg1)
	ret0, _ := ret[0].(models.AuthRequestInt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AuthRequestByID indicates an expected call of AuthRequestByID
func (mr *MockStorageMockRecorder) AuthRequestByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthRequestByID", reflect.TypeOf((*MockStorage)(nil).AuthRequestByID), arg0, arg1)
}

// CreateAuthRequest mocks base method
func (m *MockStorage) CreateAuthRequest(arg0 context.Context, arg1 *samlp.AuthnRequestType, arg2, arg3, arg4, arg5 string) (models.AuthRequestInt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAuthRequest", arg0, arg1, arg2, arg3, arg4, arg5)
	ret0, _ := ret[0].(models.AuthRequestInt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAuthRequest indicates an expected call of CreateAuthRequest
func (mr *MockStorageMockRecorder) CreateAuthRequest(arg0, arg1, arg2, arg3, arg4, arg5 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAuthRequest", reflect.TypeOf((*MockStorage)(nil).CreateAuthRequest), arg0, arg1, arg2, arg3, arg4, arg5)
}

// GetCA mocks base method
func (m *MockStorage) GetCA(arg0 context.Context) (*key.CertificateAndKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCA", arg0)
	ret0, _ := ret[0].(*key.CertificateAndKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCA indicates an expected call of GetCA
func (mr *MockStorageMockRecorder) GetCA(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCA", reflect.TypeOf((*MockStorage)(nil).GetCA), arg0)
}

// GetEntityByID mocks base method
func (m *MockStorage) GetEntityByID(arg0 context.Context, arg1 string) (*serviceprovider.ServiceProvider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntityByID", arg0, arg1)
	ret0, _ := ret[0].(*serviceprovider.ServiceProvider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntityByID indicates an expected call of GetEntityByID
func (mr *MockStorageMockRecorder) GetEntityByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntityByID", reflect.TypeOf((*MockStorage)(nil).GetEntityByID), arg0, arg1)
}

// GetEntityIDByAppID mocks base method
func (m *MockStorage) GetEntityIDByAppID(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntityIDByAppID", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntityIDByAppID indicates an expected call of GetEntityIDByAppID
func (mr *MockStorageMockRecorder) GetEntityIDByAppID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntityIDByAppID", reflect.TypeOf((*MockStorage)(nil).GetEntityIDByAppID), arg0, arg1)
}

// GetMetadataSigningKey mocks base method
func (m *MockStorage) GetMetadataSigningKey(arg0 context.Context) (*key.CertificateAndKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadataSigningKey", arg0)
	ret0, _ := ret[0].(*key.CertificateAndKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadataSigningKey indicates an expected call of GetMetadataSigningKey
func (mr *MockStorageMockRecorder) GetMetadataSigningKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadataSigningKey", reflect.TypeOf((*MockStorage)(nil).GetMetadataSigningKey), arg0)
}

// GetResponseSigningKey mocks base method
func (m *MockStorage) GetResponseSigningKey(arg0 context.Context) (*key.CertificateAndKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResponseSigningKey", arg0)
	ret0, _ := ret[0].(*key.CertificateAndKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResponseSigningKey indicates an expected call of GetResponseSigningKey
func (mr *MockStorageMockRecorder) GetResponseSigningKey(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResponseSigningKey", reflect.TypeOf((*MockStorage)(nil).GetResponseSigningKey), arg0)
}

// Health mocks base method
func (m *MockStorage) Health(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health
func (mr *MockStorageMockRecorder) Health(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockStorage)(nil).Health), arg0)
}

// SetUserinfoWithLoginName mocks base method
func (m *MockStorage) SetUserinfoWithLoginName(arg0 context.Context, arg1 models.AttributeSetter, arg2 string, arg3 []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserinfoWithLoginName", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserinfoWithLoginName indicates an expected call of SetUserinfoWithLoginName
func (mr *MockStorageMockRecorder) SetUserinfoWithLoginName(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserinfoWithLoginName", reflect.TypeOf((*MockStorage)(nil).SetUserinfoWithLoginName), arg0, arg1, arg2, arg3)
}

// SetUserinfoWithUserID mocks base method
func (m *MockStorage) SetUserinfoWithUserID(arg0 context.Context, arg1 string, arg2 models.AttributeSetter, arg3 string, arg4 []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserinfoWithUserID", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUserinfoWithUserID indicates an expected call of SetUserinfoWithUserID
func (mr *MockStorageMockRecorder) SetUserinfoWithUserID(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserinfoWithUserID", reflect.TypeOf((*MockStorage)(nil).SetUserinfoWithUserID), arg0, arg1, arg2, arg3, arg4)
}
